Repository zakirali1/Movie-Zone, pull requests merged in 2023-02, with the labels that each got.

#25 like/unlike buttons created
  assets/JS/script.js
Labels: enhancement

#29 updated selector ids for JS logic, added redirection button and country to localstorage
  assets/JS/script.js
  index_1.html
Labels: enhancement

#35 changes to likes button and dynamic movie list
  assets/JS/script.js
  index_1.html
Labels: enhancement

#38 change to code to use local storage values to re-search
  assets/JS/script.js
Labels: enhancement

#40 clean up of code
  assets/JS/script.js
Labels: documentation

#49 adding img-fluid class to poster
  assets/JS/script.js
Labels: enhancement

#50 hardcoded image height taken off
  assets/JS/script.js
Labels: enhancement

#54 changing file names and location of READme
  assets/README.md
  index.html
Labels: documentation

#56 change to rtn button location, now index.html, line 142
  assets/JS/pricesearch.js
Labels: documentation

#59 moving readmi to main
  README.md
Labels: bug

#67 movie card color adjustment - direction + colr matching
  assets/CSS/styles.css
  assets/JS/script.js
Labels: question

#74 update to api key
  assets/JS/pricesearch.js
  assets/JS/script.js
Labels: documentation
